//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lesson10_entry_framework_DTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ketqua
    {
        public string MaSV { get; set; }
        public string MaMH { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual Monhoc Monhoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
